menu:
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'google-scholar', link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Matthew Carter', title: 'Postdoctoral Scholar', department: 'Thaiss Lab', institution: 'Arc Institute', email: 'matthewmcarter2@gmail.com', image: 'assets/img/contact.jpg'}
